spring:
  application:
    name: cloud-elasticsearch
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 127.0.0.1:18848

  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: wgV1A0lM2WuNi8ZmSzwB
  data:
    elasticsearch:
      repositories:
        enabled: true


